### ISSUE TITLE
No PROJECT_HOME variable

### ISSUE THREAD

**Issue by Railslide** [SongGithub/sublime_projectfile_maker#1]
Hi,

when I try to create a new project the modules throws an error, because it cannot find PROJECT_HOME among my environment variables. 

I'd be glad to work on a fix for it.

**Comment by jpcirrus** [comment]
Not sure if I misunderstand, but you first need to set this as per the [virtualenvwrapper documentation](http://virtualenvwrapper.readthedocs.org/en/latest/install.html#variable-project-home).

**Comment by Railslide** [comment]
You don't necessarily have to export `PROJECT_HOME`. You can also add the following line to `bashrc`

```
PROJECT_HOME='/path/to/where/you/want/your/project/folder/to/be/created'
source /usr/local/bin/virtualenvwrapper.sh
```

If you set it up like this, you encounter the error about not finding the `PROJECT_HOME` variable. Hence my idea to extend the plugin to cover that case as well. However, since I haven't heard anything from the maintainer, I ended up in writing my own implementation from scratch.

**Comment by jpcirrus** [comment]
You can, but then you're making the decision that you don't want `PROJECT_HOME` available in any subprocess, and therefore to any virtualenvwrapper hook, including this one. But good that you've got a solution you're happy with.
